---

- name: Common Tasks
  hosts:
  - master
  - node
  remote_user: "{{ ansible_remote_user }}"
  gather_facts: False
  roles:
  - common

- name: Install Kubernetes master
  hosts: master
  remote_user: "{{ ansible_remote_user }}"
  become: yes
  become_method: sudo
  roles:
  - docker
  - k8s
  - master

- name: Install nodes
  remote_user: "{{ ansible_remote_user }}"
  hosts: node
  become: yes
  become_method: sudo
  roles:
  - docker
  - k8s
  - node