---

- name: kubeadm init with pre generated token
  command: kubeadm init --pod-network-cidr {{ flannel_subnet }} --token {{ kubeadm_token }}

- pause:
    minutes: 3
    prompt: "Wait for the Admin PODS"

- name: install flannel pod network
  command: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: copy config file to HOME/.kube dir
  command: "{{ item }}"
  with_items:
  - mkdir -p ~{{ansible_remote_user }}/.kube
  - cp /etc/kubernetes/admin.conf ~{{ansible_remote_user }}/.kube/config
  - chown -R {{ ansible_remote_user }}:{{ ansible_remote_user }} ~{{ansible_remote_user }}/.kube
  - chmod 0400 ~{{ansible_remote_user }}/.kube/config

- pause:
    minutes: 3
    prompt: "Make sure network pods are started"